### PR TITLE
Support L5.7

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by gotyourchalk** [comment]
Thank you for the contribution, still having an issue with install on L5.7.9

-conclusion: don't install illuminate/bus 5.6.x-dev

**Comment by AlexMordred** [comment]
@gotyourchalk hey, so is this PR good to merge the way it is?

**Comment by davidpiesse** [comment]
👍 on this :)

**Comment by AlexMordred** [comment]
Merged and released under v1.2.2. Thanks everyone!

**Pull request merged**
